"""Out-and-back path flight runner for Crazyflie 2.0.

Provides run_out_and_back_flight() — the full connection-to-landing lifecycle
for path-following scripts that use SafeFlightController.run_out_and_back().

Scripts using this runner need only define their FlightStep path and call:

    run_out_and_back_flight(MY_PATH, uri=URI, description="fly my route")

The connect -> clearance -> monitors -> takeoff-verify -> teardown lifecycle
itself lives in Crazyflie.flight.flight_lifecycle.run_flight_lifecycle(),
shared with Crazyflie.flight.wall_follow_runner. This module supplies only
the out-and-back-specific flight body: constructing SafeFlightController (and
the AdaptivePathCorrector it uses), running the path, and reacting to a
COLLISION via the optional on_collision_fn hook.
"""

import logging
from collections.abc import Callable
from pathlib import Path

from cflib.crazyflie.syncCrazyflie import SyncCrazyflie

from Crazyflie.flight.collision_return import OnCollisionFn
from Crazyflie.flight.flight_lifecycle import (
    EVENT_WAIT_TIMEOUT_S,
    FlightContext,
    FlightLifecycleHooks,
    handle_safety_events,
    run_flight_lifecycle,
)
from Crazyflie.flight.path_runner import FlightStep
from Crazyflie.flight.safe_flight_controller import SafeFlightController
from Crazyflie.safety.adaptive_path_corrector import AdaptivePathCorrector
from Crazyflie.state.flight_state import FlightState

logger = logging.getLogger(__name__)


def run_out_and_back_flight(
    path: list[FlightStep],
    uri: str,
    description: str,
    pre_flight_fn: Callable[[SyncCrazyflie], None] | None = None,
    post_flight_fn: Callable[[SyncCrazyflie], None] | None = None,
    on_collision_fn: OnCollisionFn | None = None,
    telemetry_file: Path | None = None,
) -> None:
    """Execute a path out-and-back flight with full safety architecture.

    Connects to the drone, checks clearance, starts safety monitors, verifies
    takeoff, runs the path via SafeFlightController.run_out_and_back(), then
    lands and cleans up. Blocks until the drone has disconnected and the
    post-disconnect sleep has elapsed.

    Args:
        path: Sequence of FlightSteps defining the outbound leg. The return
            leg is automatically generated by reversing the steps.
        uri: Radio or USB URI to connect to.
        description: Short description logged when the path begins, e.g.
            "fly 1 metre out and back".
        pre_flight_fn: Called after clearance check and before takeoff to
            configure the drone (e.g. LED effects). Defaults to headlights-on
            + effect 7 + brightness 31 when None.
        post_flight_fn: Called after landing to clean up (e.g. LED off).
            Defaults to turning off the LED ring when None.
        on_collision_fn: Called on a COLLISION event instead of mc.land().
            Receives the MotionCommander, a CollisionContext describing
            flight progress, a should_abort callable for detecting a second
            collision during the response, the shared FlightState, and the
            shared AdaptivePathCorrector. Defaults to mc.land() when None.
        telemetry_file: Optional path to write continuous sensor telemetry
            (every Multi-ranger reading and stabilizer sample, not just
            WARNING-level events) to as CSV. When None, no telemetry is
            recorded.
    """

    def _make_adaptive_corrector(
        scf: SyncCrazyflie, flight_state: FlightState
    ) -> AdaptivePathCorrector:
        return AdaptivePathCorrector(scf, flight_state)

    def _flight_body(ctx: FlightContext) -> None:
        controller = SafeFlightController(
            path, flight_state=ctx.flight_state, adaptive_corrector=ctx.adaptive_corrector
        )

        logger.info(f"Flying {description}...")
        controller.run_out_and_back(ctx.mc, should_abort=ctx.should_abort)

        # A monitor may have triggered mid-flight, aborting the path above.
        # Its event might not be queued yet — CollisionMonitor sets
        # is_triggered() True before its blocking avoidance move finishes and
        # calls event_queue.put() — so wait rather than check once. On normal
        # completion (should_abort() False) there is nothing to wait for.
        if ctx.should_abort():
            handle_safety_events(
                ctx.event_queue,
                ctx.mc,
                ctx.stabilizer_monitor,
                controller=controller,
                collision_monitor=ctx.collision_monitor,
                on_collision_fn=on_collision_fn,
                flight_state=ctx.flight_state,
                adaptive_corrector=ctx.adaptive_corrector,
                block_timeout_s=EVENT_WAIT_TIMEOUT_S,
            )

        # A second collision inside on_collision_fn's own response (e.g.
        # during a retrace) re-arms and re-triggers collision_monitor, which
        # queues its own "COLLISION" event. That event is already fully
        # handled synchronously by on_collision_fn's should_abort check —
        # discard it here so it cannot linger and be misread by a future
        # drain.
        while not ctx.event_queue.empty():
            ctx.event_queue.get_nowait()

        logger.info("Route complete — landing.")

    hooks = FlightLifecycleHooks(
        pre_flight_fn=pre_flight_fn,
        post_flight_fn=post_flight_fn,
        make_adaptive_corrector=_make_adaptive_corrector,
    )

    run_flight_lifecycle(uri, _flight_body, hooks=hooks, telemetry_file=telemetry_file)
